#!/bin/sh
# build-selfhost.sh - cross-build the native Z8001 C compiler: compile the
# src/cc source of record WITH the Z8001 pipeline (ccz) into C900 target
# binaries cc0/cc1/cc2 + cc3, link them against crt0 + libc-z8001.a, and report
# per-pass segment sizes against the one-64K-data-segment ceiling.
#
# The source is compiled PRISTINE - the host shims in build-cc.sh are
# LP64/glibc/gcc workarounds and do not apply to the native target.  The
# selection tables (macros.c/patern.c) are generated by the host tabgen; the
# generated C is target-independent.
#
# Prereqs: build-cc.sh, build-as.sh, build-ld.sh, build-libc-z8001.sh.
set -e
HERE=$(cd "$(dirname "$0")" && pwd)
CC="$HERE/../src/cc"
# Resolved here, not left to ccz to resolve per file: ccz needs the OS include
# path, and its refusal lands in one .err file per source, where this script
# reports it as `FAIL <pass>' -- 87 compile failures for one unset variable.
. "$HERE/coherent-os.sh"		# $COHERENT_OS, or refuse by name
. "$HERE/publish.sh"			# $BUILD, stagecopy, publish_dir
. "$HERE/provenance.sh"			# prov_get, prov_repo, prov_srcid
CCZ="$HERE/ccz"
OUT=$(stagecopy selfhost)		# carries the object cache forward
trap 'rm -rf "$OUT"' EXIT INT TERM

# The object cache below keys on the .c file's mtime, which says only that the
# SOURCE has not moved.  These objects are also a function of the COMPILER that
# produced them, and that half moved unseen: a selection-table (.t) change
# regenerates the tables and rebuilds the cross compiler while leaving every
# cached object exactly as old as it was, so the passes linked here mix codegen
# from two compilers -- which the self-host fixpoint then reports as 30 files
# whose object bytes differ, in the front end, for no reason in any of them.
#
# So the cache is keyed on the compiler's identity too.  `tcid' names the source
# the published cross compiler was built from; the tables are named live as well
# because THIS script generates them from the .t grammar, so they can move ahead
# of a compiler that was not rebuilt.  A tree that is not a checkout yields
# `unknown' for both and the cache degrades to the mtime it had before.
CACHEID="$(prov_get "$BUILD/z8001/.provenance" tcid) $(prov_srcid "$(prov_repo "$HERE")" src/cc/n1/tables)"
if [ "$(cat "$OUT/.cacheid" 2>/dev/null)" != "$CACHEID" ]; then
	[ -d "$OUT/n0" ] && echo "compiler identity changed ($CACHEID) -- discarding the object cache"
	rm -rf "$OUT/common" "$OUT/n0" "$OUT/n1" "$OUT/n2" "$OUT/n3" "$OUT/commch" "$OUT/tables"
	echo "$CACHEID" > "$OUT/.cacheid"
fi

mkdir -p "$OUT/common" "$OUT/n0" "$OUT/n1" "$OUT/n2" "$OUT/n3" "$OUT/commch" "$OUT/tables"

# selection tables: host tabgen over the pristine .t grammar
if [ ! -f "$OUT/tables/macros.c" ]; then
	cp "$CC"/n1/tables/*.t "$CC"/n1/tables/prefac.f "$OUT/tables/"
	( cd "$OUT/tables" && "$BUILD/tabgen" -s prefac.f *.t >/dev/null )
fi

INC="-I$CC/n1/z8001 -I$CC/n0/z8001 -I$CC/h/z8001 -I$CC/generated -I$CC/n0 -I$CC/n1 -I$CC/h -I$CC/common -I$CC/n3 -I$CC/n3/z8001"

fails=0
cz() {	# cz <src.c> <out.o>
	if [ -f "$2" ] && [ "$2" -nt "$1" ]; then return 0; fi
	if "$CCZ" -c -o "$2" $INC "$1" >/dev/null 2>"$2.err"; then
		echo "OK   $(basename $2 .o)"
	else
		echo "FAIL $(basename $2 .o): $(tr '\n' ' ' < "$2.err" | cut -c1-160)"
		fails=$((fails+1))
	fi
}

COMMON="bget bput dget diag dput getvar iget iput lget lput makvar milnam mionam newlab newseg nput segnam sget sput talloc tcpy unbget"
N0="cc0 cc0key cc0sym cpp dbgt0 ddecl dope double etc expand expr fold gcandt gdecl get init lex locals sharp size stat"
N1="cc1 cc1sym code mtree0 mtree1 mtree3 node out pool reg0 sel0 sel1 snap0 tree0 tree1"
N1MD="altemp amd fixtop gen1 gen2 mtree2 mtree4 outmch reg1 sel2 snap1 table0 table1"
N2="cc2 cc2sym dbgt2 emit0 getfun optim"
N2MD="afield emit1 getcod listing optab outcoh peep"
# cc3, the IR printer.  It is not a compiler pass: it is the instrument the
# fixpoint attributes a divergence with, and it has to run ON THE TARGET because
# the target's intermediates are written in the target's memory order and no
# host program can read them.  It links the machine NAME tables (common/z8001)
# that cc0/cc1/cc2 do not.
N3="cc3 dbgt3 itree"
N3MD="icode igen"
CHNAM="mdlnam mdonam regnam tyname"

for f in $COMMON; do cz "$CC/common/$f.c"   "$OUT/common/$f.o"; done
for f in $N0;     do cz "$CC/n0/$f.c"       "$OUT/n0/$f.o"; done
cz "$CC/n0/z8001/bind.c" "$OUT/n0/bind.o"
for f in $N1;     do cz "$CC/n1/$f.c"       "$OUT/n1/$f.o"; done
for f in $N1MD;   do cz "$CC/n1/z8001/$f.c" "$OUT/n1/$f.o"; done
cz "$OUT/tables/macros.c" "$OUT/n1/macros.o"
cz "$OUT/tables/patern.c" "$OUT/n1/patern.o"
for f in $N2;     do cz "$CC/n2/$f.c"       "$OUT/n2/$f.o"; done
for f in $N2MD;   do cz "$CC/n2/z8001/$f.c" "$OUT/n2/$f.o"; done
for f in $N3;     do cz "$CC/n3/$f.c"       "$OUT/n3/$f.o"; done
for f in $N3MD;   do cz "$CC/n3/z8001/$f.c" "$OUT/n3/$f.o"; done
for f in $CHNAM;  do cz "$CC/common/z8001/$f.c" "$OUT/commch/$f.o"; done

echo "--- $fails compile failures ---"
[ "$fails" = 0 ] || exit 1

# ---- link the three passes: shared separated-I/D, text may span segments ----
lkfail=0
lk() {	# lk <out> <obj...>
	b="$1"; o="$OUT/$1"; shift
	if "$CCZ" -i -L -o "$o" "$@" >/dev/null 2>"$o.err"; then
		echo "$b: LINKED ($(wc -c < "$o") B)"
	else
		echo "$b: LINK FAILED: $(tr '\n' ' ' < "$o.err" | cut -c1-200)"
		lkfail=$((lkfail+1))
	fi
}
n0objs=""; for f in $N0 bind; do n0objs="$n0objs $OUT/n0/$f.o"; done
n1objs=""; for f in $N1 $N1MD macros patern; do n1objs="$n1objs $OUT/n1/$f.o"; done
n2objs=""; for f in $N2 $N2MD; do n2objs="$n2objs $OUT/n2/$f.o"; done
n3objs=""; for f in $N3 $N3MD; do n3objs="$n3objs $OUT/n3/$f.o"; done
for f in $CHNAM; do n3objs="$n3objs $OUT/commch/$f.o"; done
cobjs="";  for f in $COMMON; do cobjs="$cobjs $OUT/common/$f.o"; done

lk cc0 $n0objs $cobjs
lk cc1 $n1objs $cobjs
lk cc2 $n2objs $cobjs
lk cc3 $n3objs $cobjs
[ "$lkfail" = 0 ] || exit 1

# The fake root build-selfhost2.sh (S3) runs in, staged here so it is published
# by the same rename as the passes it accompanies.
sh "$HERE/selfhost-root.sh" "$OUT"

publish_dir selfhost
trap - EXIT INT TERM			# $OUT is published now
# end of build-selfhost.sh
