#!/bin/sh
# gensys.sh -- generate the C library's system-call stubs from syscalls.tab.
#
#	sh host/gensys.sh <outdir>
#
# Writes one <name>.s per table row.  ONE FILE PER STUB, not one file with all
# of them: the archive is scanned member by member, so a program links only the
# calls it makes.  A single object would put all 57 in every binary.
#
# Each stub is the trap and nothing else --
#
#	.globl	name_
#	name_:
#		sys	NN
#		ret
#
# -- so the only thing that varies between them is a name and a number, which is
# what the table holds.  brk and signal are not generated: they do more than
# trap, and live in libc/sys as hand-written source.
#
# The number is emitted in DECIMAL, once, here.  The hand-written stubs spell it
# in three bases -- 48 octal, 9 decimal, 2 hex -- which is why nothing had ever
# compared them against the kernel's dispatch table.
set -e
HERE=$(cd "$(dirname "$0")" && pwd)
. "$HERE/coherent-os.sh"
TAB="$COHERENT_OS/libc/syscalls.tab"
out=${1:-}
[ -n "$out" ] || { echo "usage: gensys.sh <outdir>" >&2; exit 2; }
[ -f "$TAB" ] || { echo "gensys.sh: no $TAB" >&2; exit 1; }
mkdir -p "$out"

n=0
while read -r name num rest; do
	case "$name" in ''|\#*) continue ;; esac
	[ -n "$num" ] || { echo "gensys.sh: $name has no number" >&2; exit 1; }
	case "$num" in *[!0-9]*) echo "gensys.sh: $name: \`$num' is not a number" >&2; exit 1 ;; esac
	[ -z "$rest" ] || { echo "gensys.sh: $name: trailing junk \`$rest'" >&2; exit 1; }
	cat > "$out/$name.s" <<EOF
/ Generated by host/gensys.sh from libc/syscalls.tab -- do not edit.
/ C interface routine for the $name system call.

.globl	${name}_

${name}_:
	sys	$num
	ret
EOF
	n=$((n + 1))
done < "$TAB"
[ "$n" -gt 0 ] || { echo "gensys.sh: $TAB named no calls" >&2; exit 1; }
echo "gensys: $n system-call stubs from $(basename "$TAB")"
