/* optab.c - n2/z8001 opcode table (DRAFT, GENERATED by tools/gen_optab.py).
 * Row order MUST match generated/opcode.h. Each row: { style, base, flags }.
 * base = MWC pst.c form-0 opcode (authentic) where available, else the
 * decoder inventory form-0; asm.c ORs the addressing hi-nibble at emit.
 * style assigned by operand-shape cluster; OF_ASMONLY/OF_IO = review. */
#include "opcode.h"
#include "OF_styles.h"

struct optab { short style; unsigned short base; short flags; } optab[] = {
    { OF_DOP     , 0xB500, 0                },	/* ZADC       R,R [pst] */
    { OF_DOP     , 0xB400, OP_BYTE          },	/* ZADCB      Rb,Rb [pst] */
    { OF_DOP     , 0x0100, 0                },	/* ZADD       R,#i R,@R R,R R,addr R,addr(R) [pst] */
    { OF_DOPB    , 0x0000, OP_BYTE          },	/* ZADDB      Rb,#i Rb,@R Rb,Rb Rb,addr Rb,a [pst] */
    { OF_DOPL    , 0x1600, OP_DWORD         },	/* ZADDL      RR,#i RR,@R RR,RR RR,addr RR,a [pst] */
    { OF_DOP     , 0x0700, 0                },	/* ZAND       R,#i R,@R R,R R,addr R,addr(R) [pst] */
    { OF_DOPB    , 0x0600, OP_BYTE          },	/* ZANDB      Rb,#i Rb,@R Rb,Rb Rb,addr Rb,a [pst] */
    { OF_BIT     , 0x2700, 0                },	/* ZBIT       @R,#i R,#i R,R addr(R),#i addr [pst] */
    { OF_BIT     , 0x2600, OP_BYTE          },	/* ZBITB      @R,#i Rb,#i Rb,R addr(R),#i ad [pst] */
    { OF_CALL    , 0x1F00, OP_DWORD         },	/* ZCALL      @R addr addr(R) [pst] */
    { OF_CALR    , 0xD000, 0                },	/* ZCALR      addr [pst] */
    { OF_SOP     , 0x0D08, 0                },	/* ZCLR       @R R addr addr(R) [pst] */
    { OF_SOPB    , 0x0C08, OP_BYTE          },	/* ZCLRB      @R Rb addr addr(R) [pst] */
    { OF_SOP     , 0x0D00, 0                },	/* ZCOM       @R R addr addr(R) [pst] */
    { OF_SOPB    , 0x0C00, OP_BYTE          },	/* ZCOMB      @R Rb addr addr(R) [pst] */
    { OF_FLAG    , 0x8D05, 0                },	/* ZCOMFLG    #i [pst] */
    { OF_CP      , 0x0B00, 0                },	/* ZCP        @R,#i R,#i R,@R R,R R,addr R,a [pst] */
    { OF_CP      , 0x0A00, OP_BYTE          },	/* ZCPB       @R,#i Rb,#i Rb,@R Rb,Rb Rb,add [pst] */
    { OF_ASMONLY , 0xBB08, OP_DWORD         },	/* ZCPD       @RR,@RR,R [pst] */
    { OF_ASMONLY , 0xBA08, OP_BYTE          },	/* ZCPDB      @RR,@RR,R [pst] */
    { OF_ASMONLY , 0xBB0C, OP_DWORD         },	/* ZCPDR      @RR,@RR,R [pst] */
    { OF_ASMONLY , 0xBA0C, OP_BYTE          },	/* ZCPDRB     @RR,@RR,R [pst] */
    { OF_ASMONLY , 0xBB00, OP_DWORD         },	/* ZCPI       @RR,@RR,R [pst] */
    { OF_ASMONLY , 0xBA00, OP_BYTE          },	/* ZCPIB      @RR,@RR,R [pst] */
    { OF_ASMONLY , 0xBB04, OP_DWORD         },	/* ZCPIR      @RR,@RR,R [pst] */
    { OF_ASMONLY , 0xBA04, OP_BYTE          },	/* ZCPIRB     @RR,@RR,R [pst] */
    { OF_DOPL    , 0x1000, OP_DWORD         },	/* ZCPL       RR,#i RR,@R RR,RR RR,addr RR,a [pst] */
    { OF_ASMONLY , 0xBB0A, OP_DWORD         },	/* ZCPSD      @RR,@RR,R [pst] */
    { OF_ASMONLY , 0xBA0A, OP_BYTE          },	/* ZCPSDB     @RR,@RR,R [pst] */
    { OF_ASMONLY , 0xBB0E, OP_DWORD         },	/* ZCPSDR     @RR,@RR,R [pst] */
    { OF_ASMONLY , 0xBA0E, OP_BYTE          },	/* ZCPSDRB    @RR,@RR,R [pst] */
    { OF_ASMONLY , 0xBB02, OP_DWORD         },	/* ZCPSI      @RR,@RR,R [pst] */
    { OF_ASMONLY , 0xBA02, OP_BYTE          },	/* ZCPSIB     @RR,@RR,R [pst] */
    { OF_ASMONLY , 0xBB06, OP_DWORD         },	/* ZCPSIR     @RR,@RR,R [pst] */
    { OF_ASMONLY , 0xBA06, OP_BYTE          },	/* ZCPSIRB    @RR,@RR,R [pst] */
    { OF_ROT     , 0xB000, 0                },	/* ZDAB       Rb [pst] */
    { OF_INCDEC  , 0x2B00, 0                },	/* ZDEC       @R,#i R,#i addr(R),#i addr,#i [pst] */
    { OF_INCDEC  , 0x2A00, OP_BYTE          },	/* ZDECB      @R,#i Rb,#i addr(R),#i addr,#i [pst] */
    { OF_IMPL    , 0x7C03, 0                },	/* ZDI         NVI VI VI+NVI [pst] */
    { OF_MUL     , 0x1B00, OP_DWORD         },	/* ZDIV       RR,#i RR,@R RR,R RR,addr RR,ad [pst] */
    { OF_MUL     , 0x1A00, OP_DWORD         },	/* ZDIVL      RQ,#i RQ,@R RQ,RR RQ,addr RQ,a [pst] */
    { OF_DJNZ    , 0xF080, 0                },	/* ZDJNZ      R,addr Rb,addr [pst] */
    { OF_IMPL    , 0x7C07, 0                },	/* ZEI         NVI VI VI+NVI [pst] */
    { OF_IMPL    , 0x0E00, 0                },	/* ZEPU        [inv] */
    { OF_EX      , 0x2D00, 0                },	/* ZEX        R,@R R,R R,addr R,addr(R) [pst] */
    { OF_EX      , 0x2C00, OP_BYTE          },	/* ZEXB       Rb,@R Rb,Rb Rb,addr Rb,addr(R) [pst] */
    { OF_EXTS    , 0xB10A, OP_DWORD         },	/* ZEXTS      RR [pst] */
    { OF_EXTS    , 0xB100, OP_BYTE          },	/* ZEXTSB     RR [pst] */
    { OF_EXTS    , 0xB107, OP_DWORD         },	/* ZEXTSL     RR [pst] */
    { OF_IMPL    , 0x7A00, 0                },	/* ZHALT       [pst] */
    { OF_ASMONLY , 0x0C00, OP_DWORD         },	/* ZILLEGAL    @R @RR,@RR,R R RR Rb Rb,0 Rb, [inv] */
    { OF_IO      , 0x3D00, 0                },	/* ZIN        R,addr Rb,@R [pst] */
    { OF_IO      , 0x3C00, OP_BYTE          },	/* ZINB       Rb,@R Rb,addr [pst] */
    { OF_INCDEC  , 0x2900, 0                },	/* ZINC       @R,#i R,#i addr(R),#i addr,#i [pst] */
    { OF_INCDEC  , 0x2800, OP_BYTE          },	/* ZINCB      @R,#i Rb,#i addr(R),#i addr,#i [pst] */
    { OF_ASMONLY , 0x3B08, OP_DWORD         },	/* ZINDR      @RR,@RR,R [pst] */
    { OF_ASMONLY , 0x3A08, OP_BYTE          },	/* ZINDRB     @RR,@RR,R [inv] */
    { OF_ASMONLY , 0x3B00, OP_DWORD         },	/* ZINIR      @RR,@RR,R [pst] */
    { OF_ASMONLY , 0x3A00, OP_BYTE          },	/* ZINIRB     @RR,@RR,R [pst] */
    { OF_IMPL    , 0x7B00, 0                },	/* ZIRET       [pst] */
    { OF_JP      , 0x1E00, 0                },	/* ZJP        cc,@R cc,addr cc,addr(R) [pst] */
    { OF_JR      , 0xE000, 0                },	/* ZJR        cc,addr [pst] */
    { OF_LD      , 0x2100, 0                },	/* ZLD        @R,#i @R,R R(R),R R,#i R,@R R, [pst] */
    { OF_LDA     , 0x3400, OP_DWORD         },	/* ZLDA       R,R(R) R,addr R,addr(R) RR,add [pst] */
    { OF_LDA     , 0x3400, 0                },	/* ZLDAR      R,addr [pst] */
    { OF_LD      , 0x2000, OP_BYTE          },	/* ZLDB       @R,#i @R,Rb R(R),Rb Rb,#i Rb,@ [pst] */
    { OF_LDCTL_  , 0x7D00, OP_DWORD         },	/* ZLDCTL     CTRb,R FCW,R NSPOFF,R NSPSEG,R [pst] */
    { OF_ASMONLY, 0x0000, 0 },	/* ZLDCTLBFLAGSRB (no inventory row) */
    { OF_ASMONLY, 0x0000, 0 },	/* ZLDCTLBRBFLAGS (no inventory row) */
    { OF_ASMONLY , 0xBB09, OP_DWORD         },	/* ZLDDR      @RR,@RR,R [pst] */
    { OF_ASMONLY , 0xBA09, OP_BYTE          },	/* ZLDDRB     @RR,@RR,R [pst] */
    { OF_ASMONLY , 0xBB01, OP_DWORD         },	/* ZLDIR      @RR,@RR,R [pst] */
    { OF_ASMONLY , 0xBA01, OP_BYTE          },	/* ZLDIRB     @RR,@RR,R [pst] */
    { OF_LDK     , 0xBD00, 0                },	/* ZLDK       R,addr [pst] */
    { OF_LD      , 0x1400, OP_DWORD         },	/* ZLDL       @R,RR R(R),RR RR,#i RR,@R RR,R [pst] */
    { OF_LDM     , 0x0000, 0                },	/* ZLDM       @R,R,#i R,@R,#i R,addr(R),#i R [pst] */
    { OF_CALL    , 0x3900, 0                },	/* ZLDPS      @R addr addr(R) [pst] */
    { OF_IMPL    , 0x7B0A, 0                },	/* ZMBIT       [pst] */
    { OF_IMPL    , 0x7B0D, 0                },	/* ZMREQ       [pst] */
    { OF_IMPL    , 0x7B09, 0                },	/* ZMRES       [pst] */
    { OF_IMPL    , 0x7B08, 0                },	/* ZMSET       [pst] */
    { OF_MUL     , 0x1900, OP_DWORD         },	/* ZMULT      RR,#i RR,@R RR,R RR,addr RR,ad [pst] */
    { OF_MUL     , 0x1800, OP_DWORD         },	/* ZMULTL      RQ,RR RQ,addr RQ,addr(R) [pst] */
    { OF_SOP     , 0x0D02, 0                },	/* ZNEG       @R R addr addr(R) [pst] */
    { OF_SOPB    , 0x0C02, OP_BYTE          },	/* ZNEGB      @R Rb addr addr(R) [pst] */
    { OF_IMPL    , 0x8D07, 0                },	/* ZNOP       R [pst] */
    { OF_DOP     , 0x0500, 0                },	/* ZOR        R,#i R,@R R,R R,addr R,addr(R) [pst] */
    { OF_DOPB    , 0x0400, OP_BYTE          },	/* ZORB       Rb,#i Rb,@R Rb,Rb Rb,addr Rb,a [pst] */
    { OF_ASMONLY , 0x3B0A, OP_DWORD         },	/* ZOTDR      @RR,@RR,R [pst] */
    { OF_ASMONLY , 0x3A0A, OP_BYTE          },	/* ZOTDRB     @RR,@RR,R [pst] */
    { OF_ASMONLY , 0x3B02, OP_DWORD         },	/* ZOTIR      @RR,@RR,R [pst] */
    { OF_ASMONLY , 0x3A02, OP_BYTE          },	/* ZOTIRB     @RR,@RR,R [pst] */
    { OF_IO      , 0x3F00, 0                },	/* ZOUT       @R,R addr,R [pst] */
    { OF_IO      , 0x3E00, OP_BYTE          },	/* ZOUTB      @R,Rb addr,Rb [pst] */
    { OF_POP     , 0x1700, 0                },	/* ZPOP       R,@R addr(R),@R addr,@R [pst] */
    { OF_POP     , 0x1500, OP_DWORD         },	/* ZPOPL      @R,@RR RR,@R addr(R),@R addr,@ [pst] */
    { OF_PUSH    , 0x1300, 0                },	/* ZPUSH      @R,#i @R,R @R,addr @R,addr(R) [pst] */
    { OF_PUSH    , 0x1100, OP_DWORD         },	/* ZPUSHL     @R,@RR @R,RR @R,addr @R,addr(R [pst] */
    { OF_BIT     , 0x2300, 0                },	/* ZRES       @R,#i R,#i R,R addr(R),#i addr [pst] */
    { OF_BIT     , 0x2200, OP_BYTE          },	/* ZRESB      @R,#i Rb,#i Rb,R addr(R),#i ad [pst] */
    { OF_FLAG    , 0x8D03, 0                },	/* ZRESFLG    #i [pst] */
    { OF_RET     , 0x9E00, 0                },	/* ZRET       cc [pst] */
    { OF_ROT     , 0xB300, OP_DWORD         },	/* ZRL        R [pst] */
    { OF_ROT     , 0xB200, OP_BYTE          },	/* ZRLB       Rb [pst] */
    { OF_ROT     , 0xB308, 0                },	/* ZRLC       R [pst] */
    { OF_ROT     , 0xB208, OP_BYTE          },	/* ZRLCB      Rb [pst] */
    { OF_ROT     , 0xBE00, 0                },	/* ZRLDB      Rb,R [pst] */
    { OF_ROT     , 0xB304, 0                },	/* ZRR        R [pst] */
    { OF_ROT     , 0xB204, OP_BYTE          },	/* ZRRB       Rb [pst] */
    { OF_ROT     , 0xB30C, 0                },	/* ZRRC       R [pst] */
    { OF_ROT     , 0xB20C, OP_BYTE          },	/* ZRRCB      Rb [pst] */
    { OF_ROT     , 0xBC00, 0                },	/* ZRRDB      Rb,R [pst] */
    { OF_DOP     , 0xB700, 0                },	/* ZSBC       R,R [pst] */
    { OF_DOP     , 0xB600, OP_BYTE          },	/* ZSBCB      Rb,Rb [pst] */
    { OF_FLAG    , 0x7F00, 0                },	/* ZSC        #i [pst] */
    { OF_SHIFTD  , 0x330B, 0                },	/* ZSDA       R,R [pst] */
    { OF_SHIFTD  , 0x320B, OP_BYTE          },	/* ZSDAB      Rb,R [pst] */
    { OF_SHIFTD  , 0x330F, OP_DWORD         },	/* ZSDAL      RR,R [pst] */
    { OF_SHIFTD  , 0x3303, OP_DWORD         },	/* ZSDL       R,R [pst] */
    { OF_SHIFTD  , 0x3203, OP_BYTE          },	/* ZSDLB      Rb,R [pst] */
    { OF_SHIFTD  , 0x3307, OP_DWORD         },	/* ZSDLL      RR,R [pst] */
    { OF_BIT     , 0x2500, 0                },	/* ZSET       @R,#i R,#i R,R addr(R),#i addr [pst] */
    { OF_BIT     , 0x2400, OP_BYTE          },	/* ZSETB      @R,#i Rb,#i Rb,R addr(R),#i ad [pst] */
    { OF_FLAG    , 0x8D01, 0                },	/* ZSETFLG    #i [pst] */
    { OF_IO      , 0x3B05, 0                },	/* ZSIN       R,addr [pst] */
    { OF_IO      , 0x3A05, OP_BYTE          },	/* ZSINB      Rb,addr [pst] */
    { OF_ASMONLY , 0x3B09, OP_DWORD         },	/* ZSINDR     @RR,@RR,R [pst] */
    { OF_ASMONLY , 0x3A09, OP_BYTE          },	/* ZSINDRB    @RR,@RR,R [pst] */
    { OF_ASMONLY , 0x3B01, OP_DWORD         },	/* ZSINIR     @RR,@RR,R [pst] */
    { OF_ASMONLY , 0x3A01, OP_BYTE          },	/* ZSINIRB    @RR,@RR,R [pst] */
    { OF_SHIFT   , 0xB309, 0                },	/* ZSLA       R,0 [pst] */
    { OF_SHIFT   , 0xB209, OP_BYTE          },	/* ZSLAB      Rb,0 [pst] */
    { OF_SHIFT   , 0xB30D, OP_DWORD         },	/* ZSLAL      RR,0 [pst] */
    { OF_SHIFT   , 0xB301, OP_DWORD         },	/* ZSLL       R,0 [pst] */
    { OF_SHIFT   , 0xB201, OP_BYTE          },	/* ZSLLB      Rb,0 [pst] */
    { OF_SHIFT   , 0xB305, OP_DWORD         },	/* ZSLLL      RR,0 [pst] */
    { OF_ASMONLY , 0x3B0B, OP_DWORD         },	/* ZSOTDR     @RR,@RR,R [pst] */
    { OF_ASMONLY , 0x3A0B, OP_BYTE          },	/* ZSOTDRB    @RR,@RR,R [pst] */
    { OF_ASMONLY , 0x3B03, OP_DWORD         },	/* ZSOTIR     @RR,@RR,R [pst] */
    { OF_ASMONLY , 0x3A03, OP_BYTE          },	/* ZSOTIRB    @RR,@RR,R [pst] */
    { OF_IO      , 0x3B07, 0                },	/* ZSOUT      addr,R [pst] */
    { OF_IO      , 0x3A07, OP_BYTE          },	/* ZSOUTB     addr,Rb [pst] */
    { OF_DOP     , 0x0300, 0                },	/* ZSUB       R,#i R,@R R,R R,addr R,addr(R) [pst] */
    { OF_DOPB    , 0x0200, OP_BYTE          },	/* ZSUBB      Rb,#i Rb,@R Rb,Rb Rb,addr Rb,a [pst] */
    { OF_DOPL    , 0x1200, OP_DWORD         },	/* ZSUBL      RR,#i RR,@R RR,RR RR,addr RR,a [pst] */
    { OF_TCC     , 0xAF00, 0                },	/* ZTCC       cc,R [pst] */
    { OF_TCC     , 0xAE00, OP_BYTE          },	/* ZTCCB      cc,Rb [pst] */
    { OF_SOP     , 0x0D04, 0                },	/* ZTEST      @R R addr addr(R) [pst] */
    { OF_SOPB    , 0x0C04, OP_BYTE          },	/* ZTESTB     @R Rb addr addr(R) [pst] */
    { OF_SOP     , 0x1C08, OP_DWORD         },	/* ZTESTL     @R RR addr addr(R) [pst] */
    { OF_ASMONLY , 0xB808, OP_DWORD         },	/* ZTRDB      @RR,@RR,R [pst] */
    { OF_ASMONLY , 0xB80C, OP_DWORD         },	/* ZTRDRB     @RR,@RR,R [pst] */
    { OF_ASMONLY , 0xB800, OP_DWORD         },	/* ZTRIB      @RR,@RR,R [pst] */
    { OF_ASMONLY , 0xB804, OP_DWORD         },	/* ZTRIRB     @RR,@RR,R [pst] */
    { OF_ASMONLY , 0xB80A, OP_DWORD         },	/* ZTRTDB     @RR,@RR,R [pst] */
    { OF_ASMONLY , 0xB80E, OP_DWORD         },	/* ZTRTDRB    @RR,@RR,R [pst] */
    { OF_ASMONLY , 0xB802, OP_DWORD         },	/* ZTRTIB     @RR,@RR,R [pst] */
    { OF_ASMONLY , 0xB806, OP_DWORD         },	/* ZTRTIRB    @RR,@RR,R [pst] */
    { OF_SOP     , 0x0D06, 0                },	/* ZTSET      @R R addr addr(R) [pst] */
    { OF_SOPB    , 0x0C06, OP_BYTE          },	/* ZTSETB     @R Rb addr addr(R) [pst] */
    { OF_DOP     , 0x0900, 0                },	/* ZXOR       R,#i R,@R R,R R,addr R,addr(R) [pst] */
    { OF_DOPB    , 0x0800, OP_BYTE          },	/* ZXORB      Rb,#i Rb,@R Rb,Rb Rb,addr Rb,a [pst] */
};
